import type { Track } from "./types";

export const tracksData: Track[] = [
    { id: "BadBunny001", name: "Safaera", duration: "4:53", artist: "BadBunny_artist" },
    { id: "BadBunny002", name: "Dákiti", duration: "3:25", artist: "BadBunny_artist" },
    { id: "BadBunny003", name: "Tití Me Preguntó", duration: "4:03", artist: "BadBunny_artist" },
    { id: "BadBunny004", name: "Me Porto Bonito", duration: "3:59", artist: "BadBunny_artist" },
    { id: "BadBunny005", name: "Callaíta", duration: "4:10", artist: "BadBunny_artist" },
    { id: "BadBunny006", name: "NADIE SABE", duration: "6:19", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny007", name: "MÓNACO", duration: "4:27", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny008", name: "FINA", duration: "3:36", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny009", name: "HIBIKI", duration: "3:28", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny010", name: "MR. OCTOBER", duration: "3:09", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny011", name: "CYBERTRUCK", duration: "3:11", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny012", name: "VOU 787", duration: "2:03", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny013", name: "SEDA", duration: "3:10", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny014", name: "GRACIAS POR NADA", duration: "2:56", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny015", name: "TELEFONO NUEVO", duration: "5:54", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny016", name: "BABY NUEVA", duration: "4:00", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny017", name: "MERCEDES CAROTA", duration: "3:22", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny018", name: "LOS PITS", duration: "4:10", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny019", name: "VUELVE CANDY B", duration: "4:26", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny020", name: "BATICANO", duration: "4:16", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny021", name: "NO ME QUIERO CASAR", duration: "3:45", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny022", name: "WHERE SHE GOES", duration: "3:51", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny023", name: "THUNDER Y LIGHTNING", duration: "3:37", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny024", name: "PERRO NEGRO", duration: "2:42", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny025", name: "EUROPA :(", duration: "0:11", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny026", name: "ACHO PR", duration: "5:59", artist: "BadBunny_artist", album: "BadBunny_album_001" },
    { id: "BadBunny027", name: "UN PREVIEW", duration: "2:45", artist: "BadBunny_artist", album: "BadBunny_album_001" },

    { id: "BadBunny028", name: "EL MUNDO ES MIO", duration: "3:52", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny029", name: "YA ME FUI", duration: "3:15", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny030", name: "VEN ENSEÑAME", duration: "3:46", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny031", name: "LO QUE PASO PASO", duration: "4:10", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny032", name: "BANG BANG", duration: "3:13", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny033", name: "SOBREDOSIS", duration: "4:30", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny034", name: "TENGO", duration: "2:51", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny035", name: "YA NO TE VEO", duration: "3:22", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny036", name: "NO VUELVAS", duration: "4:01", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny037", name: "UN PELO", duration: "3:27", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny038", name: "ME DEJASTE", duration: "2:49", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny039", name: "EL PUEBLO", duration: "3:56", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny040", name: "AL PRINCIPIO", duration: "4:08", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny041", name: "DESPUES DE ESTA", duration: "3:45", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny042", name: "CONQUISTANDO", duration: "4:22", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny043", name: "CERO", duration: "3:59", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny044", name: "SIGO", duration: "3:33", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny045", name: "TE LO DIJE", duration: "4:04", artist: "BadBunny_artist", album: "BadBunny_album_002" },
    { id: "BadBunny046", name: "LIBERACION", duration: "5:01", artist: "BadBunny_artist", album: "BadBunny_album_002" },


    { id: "Aitana001", name: "Formentera", duration: "3:10", artist: "Aitana_artist" },
    { id: "Aitana002", name: "Mon Amour", duration: "3:06", artist: "Aitana_artist" },
    { id: "Aitana003", name: "En el Coche", duration: "2:59", artist: "Aitana_artist" },
    { id: "Aitana004", name: "+ (Más)", duration: "3:36", artist: "Aitana_artist" },
    { id: "Aitana005", name: "Teléfono", duration: "3:34", artist: "Aitana_artist" },

    { id: "Feid001", name: "ALAKRAN", duration: "1:30", artist: "Feid_artist", album: "Feid_album_001" },
    { id: "Feid002", name: "50 PALOS", duration: "2:47", artist: "Feid_artist", album: "Feid_album_001" },
    { id: "Feid003", name: "LA VUELTA", duration: "2:01", artist: "Feid_artist", album: "Feid_album_001" },
    { id: "Feid004", name: "CUAL ES ESA", duration: "2:52", artist: "Feid_artist", album: "Feid_album_001" },
    { id: "Feid005", name: "INTERLUDE", duration: "1:43", artist: "Feid_artist", album: "Feid_album_001" },
    { id: "Feid006", name: "LUNA", duration: "3:16", artist: "Feid_artist", album: "Feid_album_001" },
    { id: "Feid007", name: "ESQUIRLA", duration: "2:27", artist: "Feid_artist", album: "Feid_album_001" },
    { id: "Feid008", name: "DESQUITE", duration: "2:13", artist: "Feid_artist", album: "Feid_album_001" },
    { id: "Feid009", name: "YO AK", duration: "3:25", artist: "Feid_artist", album: "Feid_album_001" },
    { id: "Feid010", name: "CLASSY 101", duration: "3:15", artist: "Feid_artist", album: "Feid_album_001" },


    { id: "Quevedo001", name: "Quédate", duration: "3:24", artist: "Quevedo_artist" },
    { id: "Quevedo002", name: "Punto G", duration: "2:54", artist: "Quevedo_artist" },
    { id: "Quevedo003", name: "Ahora y Siempre", duration: "3:17", artist: "Quevedo_artist" },
    { id: "Quevedo004", name: "Yatekomo", duration: "2:50", artist: "Quevedo_artist" },
    { id: "Quevedo005", name: "Playa del Inglés", duration: "3:12", artist: "Quevedo_artist" },
    { id: "Quevedo006", name: "KASSANDRA", duration: "3:03", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo007", name: "DURO", duration: "2:42", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo008", name: "IGUALES", duration: "3:03", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo009", name: "GRAN VÍA", duration: "3:33", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo010", name: "CHAPIADORA.COM", duration: "3:17", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo011", name: "POR ATRÁS", duration: "2:51", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo012", name: "14 FEBREROS", duration: "2:52", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo013", name: "LA 125", duration: "3:14", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo014", name: "HALO", duration: "3:01", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo015", name: "MR. MOONDIAL", duration: "2:45", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo016", name: "QUE ASCO DE TODO", duration: "3:10", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo017", name: "NOEMÚ", duration: "3:26", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo018", name: "SHIBATTO", duration: "2:18", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo019", name: "LOS DÍAS CONTADOS", duration: "2:41", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo020", name: "EL ESTRIBILLO", duration: "2:41", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo021", name: "AMANECIÓ", duration: "4:15", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo022", name: "TE FALLÉ", duration: "3:39", artist: "Quevedo_artist", album: "Quevedo_album_001" },
    { id: "Quevedo023", name: "BUENAS NOCHES", duration: "3:58", artist: "Quevedo_artist", album: "Quevedo_album_001" },


    { id: "Morat001", name: "A Dónde Vamos?", duration: "3:24", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat002", name: "No Termino", duration: "4:00", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat003", name: "En Coma", duration: "3:23", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat004", name: "Al Aire", duration: "2:49", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat005", name: "De Cero", duration: "3:07", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat006", name: "Primeras Veces", duration: "3:12", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat007", name: "No Hay Más Que Hablar", duration: "3:31", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat008", name: "Enamórate De Alguien Más", duration: "3:49", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat009", name: "Date La Vuelta", duration: "3:17", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat010", name: "Idiota", duration: "3:03", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat011", name: "Bajo La Mesa", duration: "2:37", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat012", name: "Nunca Te Olvidé", duration: "3:32", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat013", name: "Mi Pesadilla", duration: "3:25", artist: "Morat_artist", album: "Morat_album_001" },
    { id: "Morat014", name: "Simplemente Pasan", duration: "3:01", artist: "Morat_artist", album: "Morat_album_001" },

    
    { id: "MykeTowers001", name: "COMPETENCIA", duration: "3:10", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers002", name: "OTRA OPORTUNIDAD", duration: "2:49", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers003", name: "AUNQUE LLEGUE OTRO", duration: "3:17", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers004", name: "MEJOR ASI", duration: "3:39", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers005", name: "TAMBIÉN", duration: "2:19", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers006", name: "FRÍO", duration: "2:40", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers007", name: "CACHÉ", duration: "3:16", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers008", name: "SEXO DESENFRENADO", duration: "4:03", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers009", name: "LA PRIMERA VEZ", duration: "2:51", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers010", name: "PODER ADQUISITIVO", duration: "3:01", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers011", name: "VENENOSA", duration: "2:52", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers012", name: "OTRA NOCHE", duration: "3:44", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers013", name: "SE TE NOTA", duration: "3:10", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers014", name: "HASTA LA VISTA", duration: "2:54", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers015", name: "DINERO y FAMA", duration: "3:35", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers016", name: "EN EL MAR", duration: "4:06", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers017", name: "VAMO A DARLE", duration: "2:56", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers018", name: "DIABLITA", duration: "3:05", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers019", name: "ADIVINO", duration: "4:38", artist: "MykeTowers_artist", album: "MykeTowers_001" },
    { id: "MykeTowers020", name: "HASTA LUEGO", duration: "3:02", artist: "MykeTowers_artist", album: "MykeTowers_001" },


    { id: "Melendi001", name: "Caminando por la Vida", duration: "3:19", artist: "Melendi_artist" },
    { id: "Melendi002", name: "Tu Jardín con Enanitos", duration: "4:20", artist: "Melendi_artist" },
    { id: "Melendi003", name: "La Promesa", duration: "3:59", artist: "Melendi_artist" },
    { id: "Melendi004", name: "Desde Que Estamos Juntos", duration: "3:40", artist: "Melendi_artist" },
    { id: "Melendi005", name: "Lágrimas Desordenadas", duration: "4:00", artist: "Melendi_artist" }
];
